InvestmentMonitor/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("accounts/", include("allauth.urls")),
    path("", include("pages.urls", namespace="pages")),
]

pages/urls.py
from django.urls import path
from .views import list_stocks,create_stock,edit_stock,delete_stock

from . import views

app_name = "pages"

urlpatterns = [
    path("", views.HomePageView.as_view(), name="home"),
    path("lista/", list_stocks, name="list_stocks"),
    path("novo/",create_stock, name="create_stock"),
    path("editar/<int:id>/",edit_stock, name='edit_stock'),
    path("deletar/<int:id>/",delete_stock, name='delete_stock'),
]

pages/models.py
from django.db import models


# Create your models here.


class Stock(models.Model):
    Codigo = models.CharField(max_length=6)
    Preço = models.DecimalField(max_digits=9, decimal_places=2)
    Quantidade = models.IntegerField()
    Data = models.DateField()

    def __str__(self):
        return self.Codigo

pages/forms.py
from django import forms
from .models import Stock


class StockForm(forms.ModelForm):
    class Meta:
        model = Stock
        fields = ['Codigo','Preço','Quantidade','Data']

pages/views.py
from django.views.generic import TemplateView
from django.shortcuts import render, redirect
from .models import Stock
from .forms import StockForm


class HomePageView(TemplateView):
    template_name = "home.html"


def list_stocks(request):
    stocks = Stock.objects.all()
    return render(request, 'stock-list.html', {'stocks': stocks})  

def create_stock(request):
    form = StockForm(request.POST or None)
    if form.is_valid():
        form.save()
        return redirect('pages:list_stocks')

    return render(request, 'stocks-form.html', {'form': form})  

def edit_stock(request, id):
    stock = Stock.objects.get(id=id)
    form = StockForm(request.POST or None, instance=stock)
    if form.is_valid():
        form.save()
        return redirect('pages:list_stocks')

    return render(request, 'stocks-form.html', {'form': form, 'stock': stock})  

def delete_stock(request, id):
    stock = Stock.objects.get(id=id)

    if request.method == 'POST':
        stock.delete()
        return redirect('pages:list_stocks')

    return render(request, 'stocks-delete-confirm.html', {'stocks': stock})  

templates/base.html
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    <title>{% block title %}{% endblock %}</title>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand navbar-dark bg-dark mb-3">
            <div class="container">
                <a class="navbar-brand" href="{% url 'pages:home' %}">Monitor de Investimentos</a>
                <ul class="navbar-nav">
                    {% if user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'account_logout' %}">Sair</a>
                    </li>
                    {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'account_login' %}">Entrar</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'account_signup' %}">Cadastro</a>
                    </li>
                    {% endif %}
                </ul>
            </div>
        </nav>
    </header>

    <main class="container">
        {% block content %}
        {% endblock %}
    </main>

    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
</body>
</html>

templates/home.html
{% extends 'base.html' %}

{% block title %}Monitor de Investimentos{% endblock %}

{% block content %}
<p>
    <a href="{% url 'pages:create_stock' %}">Novo Ativo</a>
</p>
<p>
    <a href="{% url 'pages:list_stocks' %}">Lista de Ativos</a>
</p>

<div class="scrollmenu" style="background: grey">
  <a href="{% url 'pages:create_stock' %}">Novo Ativo</a>
  <a href="{% url 'pages:list_stocks' %}">Lista de Ativos</a>
</div>
{% endblock %}

templates/stock-list.html
{% extends 'base.html' %}

{% block title %}Lista de Ativos Cadastrados{% endblock %}

{% block content %}
<ul>
    {% for stock in stocks %}
        <a href="{% url 'pages:edit_stock' stock.id %}">
            <li> Código: {{ stock.Codigo }}</li>     
            <a>Preço: R$ {{ stock.Preço }}</a>
            <p>Quantidade: {{ stock.Quantidade }}</p>
        </a>
    {% endfor %}
</ul>
{% endblock %}

templates/stocks-delete-confirm.html
{% extends 'base.html' %}
{% block content %}
    <form method="POST">
        {% csrf_token %}
        <h2>Tem certeza que quer deletar {{stock.Codigo}} ?</h2>
        <button type="submit">Sim</button>
    </form>
{% endblock %}

templates/stocks-form.html
{% extends 'base.html' %}
{% block content %}
    <form method="POST">
        {% csrf_token %}
        {% load crispy_forms_filters %}
        {{ form|crispy }}
        <button type="submit">Salvar</button>
    </form>

    {% if stock %}
    <a href="{% url 'pages:delete_stock' stock.id %}">Deletar</a>
    {% endif %}
{% endblock %}

templates/stocks.html
{% extends 'base.html' %}
{% block content %}
{% for stock in stocks %}
<ul>
    <a href="{% url 'pages:edit_stock' stock.id %}">
        <liv> {{ stock.Codigo }} </liv>
    </a>
</ul>
<a href="{% url 'pages:create_stock' %}">Novo Ativo</a>
{% endfor %}
{% endblock %}